name: ${project.name}
authors: [James Gavin]
version: ${project.version}-${git.commit.id.abbrev}
main: ${project.groupId}.Main
api-version: 1.18
website: percy.jmsgvn.com
description: Complied at ${timestamp}
